### ISSUE TITLE
Is the Bot Online?

### ISSUE THREAD

**Issue by clarissaapplebloom** [EliCDavis/PartyParrotBot#1]
I tried to interact with [@party_parrot_bot](https://telegram.me/party_parrot_bot) but it seems to be offline. May you please check, @EliCDavis?

**Comment by CrazyMarvin** [comment]
The bot is not working on my end too so I am planning to develop a new bot with @TECH-SAVVY-GUY.
The source is available on [https://github.com/Crazy-Marvin/PartyParrotsTelegramBot](https://github.com/Crazy-Marvin/PartyParrotsTelegramBot) and you may find it [on Telegram @PartyParrotsBot](https://t.me/PartyParrotsBot/). I suppose we will be ready until the end of this year. 😊

**Comment by clarissaapplebloom** [comment]
> The bot is not working on my end too so I am planning to develop a new bot with @TECH-SAVVY-GUY. The source is available on https://github.com/Crazy-Marvin/PartyParrotsTelegramBot and you may find it [on Telegram @PartyParrotsBot](https://t.me/PartyParrotsBot/). I suppose we will be ready until the end of this year. blush

Wow, that are amazing news!! Thank you so much!!

**Comment by EliCDavis** [comment]
What the fuck is going on

**Comment by clarissaapplebloom** [comment]
> What the fuck is going on

Is your bot online and I am making a mistake or did you stop its server?
I would really love to use parrots in my Telegram chats.

**Comment by EliCDavis** [comment]
Your account is 14 hours old and you're using a picture of Taylor Hill. @CrazyMarvin Did you really bot to promote a party parrot telegram app?

**Comment by CrazyMarvin** [comment]
I saw this comment and saw my chance. 😅

If you prefer, I will delete the link to my repository/bot. I was thinking about a Party Parrots Telegram Bot for quite some time and finally plan to do it. Sorry for the spammy/promoting comment.

**Comment by EliCDavis** [comment]
All of yall reported. What a fever dream.

**Comment by CrazyMarvin** [comment]
> All of yall reported. What a fever dream.

That's fine for me. Just recommending/advertising my project here was not a decent move.

May you please confirm if your Telegram bot is active or not though? I would really like to try it out without running it myself locally. Thanks.
